# Generated by Django 5.2.4 on 2025-12-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0002_quizsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
