# Generated by Django 5.2.4 on 2025-12-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0003_delete_quizsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='question',
            new_name='text',
        ),
        migrations.AddField(
            model_name='mcq',
            name='explanation',
            field=models.TextField(blank=True, help_text='Short reason why the correct option is right.'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1),
        ),
    ]
