# Generated by Django 5.2.4 on 2025-12-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0004_rename_question_mcq_text_mcq_explanation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MCQ',
            new_name='Question',
        ),
    ]
