# Generated by Django 5.2.4 on 2025-12-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0006_mcq_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
