# Generated by Django 5.2.4 on 2025-12-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0008_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options_text', models.TextField(help_text='Options separated by ||')),
                ('correct_option', models.CharField(max_length=255)),
            ],
        ),
    ]
