# Generated by Django 5.2.4 on 2025-12-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0009_mcq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
